openapi: 3.0.0
info:
  title: 'Api BileMo'
  version: '0.1'
servers:
  -
    url: 'http://localhost/api/v1'
    description: 'Api BileMo'
paths:
  '/users/{id}':
    get:
      operationId: 'App\Controller\UserController::show'
      parameters:
        -
          name: id
          in: path
          description: 'Ressource ID'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'A user'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users:
    get:
      operationId: 'App\Controller\UserController::index'
      parameters:
        -
          name: page
          in: query
          description: 'the current page'
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'List of users'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time
        customer:
          type: object
      type: object
